name: buatbesok_flutter_assets_generator
description: Buatbesok flutter tool to generate assets configs in pubspec.yaml and assets as constant variables automatically for Repro structured project
version: 0.0.1+1
homepage: https://github.com/Buat-Besok/buatbesok_flutter_assets_generator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.1
  build_runner_core: ^7.2.9
  dart_style: ^2.3.1
  io: ^1.0.4
  meta: ^1.9.1
  mime: ^1.0.4
  path: ^1.8.3
  source_span: ^1.10.0
  yaml: ^3.1.2

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_lints: ^2.0.1
  test: ^1.24.3

executables:
  assets_generator: main
