name: buatbesok_flutter_assets_generator
description: Buatbesok flutter tool to generate assets configs in pubspec.yaml and assets as constant variables automatically for Repro structured project
version: 0.0.1+1
homepage: https://github.com/Buat-Besok/buatbesok_flutter_assets_generator

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  args: ^2.4.0
  build_runner_core: ^7.2.7
  dart_style: ^2.2.4
  io: ^1.0.4
  meta: ^1.8.0
  mime: ^1.0.4
  path: ^1.8.3
  source_span: ^1.9.1
  yaml: ^3.1.1

dev_dependencies:
  dart_code_metrics: ^5.6.0
  flutter_lints: ^2.0.0
  test: ^1.23.1

flutter:
